spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: springboot
      password: springboot123
      database: springboot
      authentication-database: admin
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /