apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  labels:
    app: user-app
spec:
  replicas: 2
  template:
    metadata:
      name: user-app
      labels:
        app: user-app
    spec:
      containers:
        - name: user-app
          image: akozhin/otus-user-service:0.1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_CONFIG_LOCATION
              valueFrom:
                configMapKeyRef:
                  name: user-app-cfg
                  key: cfg-location
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb
                  key: database-name
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-password
            - name: MONGO_URL
              value: mongodb
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
          volumeMounts:
            - mountPath: /config
              name: cfg
      volumes:
        - name: cfg
          configMap:
            name: user-app-cfg
      restartPolicy: Always
  selector:
    matchLabels:
      app: user-app
