apiVersion: v1
kind: ConfigMap
metadata:
  name: user-app-cfg
data:
  application.yaml: |
    spring:
      main:
        banner-mode: off
    management:
      endpoint:
        info:
          enabled: true
        health:
          probes:
            enabled: true
      endpoints:
        web:
          base-path: /