apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otus-user-app.fullname" . }}
data:
  cfg-location: /config/application.yaml
  application.yaml: |
    spring:
      main:
        banner-mode: off
      data:
        mongodb:
          host: ${MONGO_URL}
          port: 27017
          username: ${MONGO_USERNAME}
          password: ${MONGO_PASSWORD}
          database: ${MONGO_DATABASE}
          authentication-database: admin
    management:
      endpoint:
        info:
          enabled: true
        health:
          probes:
            enabled: true
